name: Prettier Check

on: pull_request

jobs:
  prettier:
    runs-on: gha-runner-scale-set
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Run prettier
        run: npx prettier --check ./src
