name: Test
on:
  pull_request:
jobs:
  test:
    runs-on: gha-runner-scale-set
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "npm"
      - run: npm ci
      - run: npm run build
